### ISSUE TITLE
.git at root of project

### ISSUE THREAD

**Issue by GN13008** [llucasspot/boomboom-front-react-native#11]
For me it's really annoying to have .git then repo expo-boouboomapp. It's is something require by expo ? 

You need to commit from / but you need to start npm run start from /expo-boomboomapp.

You know what I mean ? ^^ 

Do we have some solution ?

**Comment by llucasspot** [comment]
Hi, not it is no required by expo, i have just run the command to create expo app and it has created a sub folder in the repo folder.
It is not really annoying the git command can be run in subfolder too ^^

**Comment by GN13008** [comment]
Okay ahah 
I just wanted to know if this subfolder had any use ^^

I close the issue :)
