### ISSUE TITLE
[Question] Design Pattern.

### ISSUE THREAD

**Issue by cimandef** [llucasspot/boomboom-front-react-native#3]
Hi there,

I noticed that you've implemented some OOP design patterns in your "boum-boum" app, particularly for API communication. I'm intrigued and would like to understand the differences, especially in the context of React (Native), between using this paradigm and opting for a library like react-query. I also came across an example of creating custom requests in your app, as shown [here](https://github.com/Angel-Dijoux/Onsiep_RN_App/blob/main/src/hooks/favoris/useAddFavoris.ts).

Could you please share insights into why you chose the OOP design pattern for API communication over a library like react-query? Additionally, how has this decision influenced the structure and performance of your app?

Thank you for your response, and by the way, the app looks nice!

**Comment by llucasspot** [comment]
Hi,

When you say OOP, I presume you talk about Object Oriented Programming.
I didn’t choose one over the other. the both can be used.
I choose to use oop to have dependancies injections to handle mocking with
my env variables EXPO_PUBLIC_MOCK_MODE. It is a great design too if you
have different logic / classes depending on the device (android / iOS). It
has many use cases.
On the other hand, react query can be used for simplify management of
asynchronous calls, data caching and pagination and infinite queries.
Exemple : { data, error, loading } = useQuery(« key », () =>
service.getList())

For the app state I use micro observable. But if you are more familiar with
react query you can use it for data synchronization and mutation management
also.

I am looking for people motivated to contribute to the app. If you are I
will be glade to work with you and we can discuss about patterns. The pull
requests are open.
I am more my self a backend developer. If you are more a front end
developer we can make a good team.

Best regards ;)

Le jeu. 4 janv. 2024 à 06:19, Angel Dijoux ***@***.***> a
écrit :

**Comment by cimandef** [comment]
Hello,

Thanks for the detailed overview of your approach to app development. I'm excited about the opportunity to contribute as a front-end developer.

Could you please provide more details on how I can get started? Are there specific tasks or features you'd like me to work on initially? I'm eager contribute to the project.

Looking forward to your guidance on how to proceed.

Best regards !

**Comment by llucasspot** [comment]
I think some user state are not well implemented on all the screen. 
And some screen are missing regarding the design provided my Benjamin 
You can start where anywhere you’d like :) 
You can make some PR :)

**Comment by cimandef** [comment]
Okay ! Thanks you, I'll start this ASAP !
